name: "\U0001F41E Bug report"
description: Create a report to help us improve AlcamelNvim 
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: os
    attributes:
      label: Operating system
      description: Your Linux distribution (can be shown by `lsb_release -a`).
      placeholder: e.g. Ubuntu 24.04
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Description
      description: Describe the expected behaviour, the actual behaviour, and the steps to reproduce.
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Neovim log
      description: The logfile of Nvim (usually `~/.local/share/nvim/log`).
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots (optional)
      description: Screenshots that might help to make the problem more clear.
    validations:
      required: false
